CREATE TABLE Cobo_monedas ([codigo] VARCHAR (50) PRIMARY KEY NOT NULL, [url_Inet] VARCHAR (50) NOT NULL, [descripcion] VARCHAR (100) DEFAULT(NULL), [valor] FLOAT (0, 0) DEFAULT(NULL), [fechaRegistro] TIMESTAMP NOT NULL);
CREATE TABLE Cobo_configuracion ([codigo] VARCHAR (50) PRIMARY KEY NOT NULL, [valor] VARCHAR (250) NOT NULL, [descripcion] VARCHAR (250) NOT NULL);
CREATE TABLE Cobo_mercado_moneda ([id] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, [nombreUrl] VARCHAR (50) NOT NULL, [abrevMoneda] VARCHAR (50) DEFAULT(NULL), [fechaRegistro] DATETIME DEFAULT(NULL));
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE Cobo_mercados ( mercado VARCHAR ( 20 ) PRIMARY KEY UNIQUE , habilitado BOOLEAN , descripcion VARCHAR ( 200 ) );
CREATE TABLE Cobo_nombreticket ([nombre] VARCHAR (50) PRIMARY KEY NOT NULL, [fechaRegistro] DATE NOT NULL DEFAULT('0000-00-00 00:00:00'), [fechaError] DATETIME DEFAULT(NULL), [fechaActualizacion] DATETIME DEFAULT(NULL), [fechahistorico] DATE DEFAULT(NULL));
CREATE TABLE Cobo_componentes ([codigo] INTEGER PRIMARY KEY NOT NULL, [nombre] VARCHAR (255) DEFAULT(NULL), [tiket] VARCHAR (50) NOT NULL REFERENCES [Cobo_nombreticket] ([nombre]), [mercado] VARCHAR (255) DEFAULT(NULL), [max52] FLOAT (0, 0) DEFAULT(NULL), [maxDia] FLOAT (0, 0) DEFAULT(NULL), [min52] FLOAT (0, 0) DEFAULT(NULL), [minDia] FLOAT (0, 0) DEFAULT(NULL), [valorActual] FLOAT (0, 0) DEFAULT(NULL), [volumenMedio] FLOAT (0, 0) DEFAULT(NULL), [volumen] FLOAT (0, 0) DEFAULT(NULL), [error] VARCHAR (255) DEFAULT(NULL), [fechaRegistro] DATE DEFAULT('0000-00-00 00:00:00'));
CREATE TABLE Cobo_params_operaciones ([id] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, [precio_ini] FLOAT (0, 0) DEFAULT(0), [precio_fin] FLOAT (0, 0) DEFAULT(0), [fecha_ini] DATETIME DEFAULT(NULL), [fecha_fin] DATETIME DEFAULT(NULL), [timing] CHAR (2) NOT NULL, [precio_salida] FLOAT (0, 0) DEFAULT(0), [salida] FLOAT (0, 0) DEFAULT(0), [entrada] FLOAT (0, 0) DEFAULT(0), [rentabilidad] FLOAT (0, 0) DEFAULT(0), [codigo] INT NOT NULL DEFAULT(0) REFERENCES [Cobo_componentes] ([codigo]));
CREATE TABLE Cobo_nombreticket_borrados ([nombre] VARCHAR (50) PRIMARY KEY NOT NULL, [fechaRegistro] DATE NOT NULL DEFAULT('0000-00-00 00:00:00'));
CREATE TABLE sqlite_stat1(tbl,idx,stat);
CREATE UNIQUE INDEX idx_Cobo_nombreticket ON [Cobo_nombreticket] ( [nombre] );
CREATE UNIQUE INDEX idx_Cobo_mercado_moneda ON [Cobo_mercado_moneda] ( [nombreUrl] ASC );
CREATE UNIQUE INDEX idx_Cobo_monedas ON [Cobo_monedas] ( [codigo] ASC );
CREATE UNIQUE INDEX idx_Cobo_params_operaciones ON [Cobo_params_operaciones] ( [codigo] ASC );
CREATE UNIQUE INDEX idx_Cobo_componentes ON [Cobo_componentes] ( [tiket] ASC );
CREATE UNIQUE INDEX idx_Cobo_mercados ON [Cobo_mercados] ( [mercado] ASC );
CREATE UNIQUE INDEX idx_Cobo_nombreticket_borrados ON [Cobo_nombreticket_borrados]([nombre]);
;
BEGIN TRANSACTION;
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^AORD', 'False', NULL);
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^AXJO', 'False', NULL);
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^BFX', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^DJI', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^DJU', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^DJT', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^DJA', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^NYA', 'False', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^DFX', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^HGX', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^OSX', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^RXS', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^UTY', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^XAU', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^SOX', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^IXHC', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^DJUSEN', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^DJUSBT', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^DJUSCH', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^IIX', 'False', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^XMI', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^STOXX50E', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^ISEQ', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^FTSE', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^FTAI', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^FTAS', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^FTMC', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^FTT1X', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^NMX0530', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^NMX2350', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^NMX3530', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^NMX3780', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^NMX4530', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^NMX5330', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^NZ50', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^BVSP', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^NSEI', 'False', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('AEX.AS', 'False', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^FCHI', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^SBF250', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^PXT', 'False', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^CIT20', 'False', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^MS190', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^CM100', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^CS90', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^SDAXI', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^GDAXI', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^TECDAX', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^MDAXI', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^MCAPM', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^HSCE', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^HSCC', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('HSNF', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^HSI', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^HSNP', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^HSNU', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^ATX', 'False', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('OMXC20.CO', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('ITSC.MI', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('ITLMS.MI', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('ITMC.MI', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('ITMI.MI', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('ITSTAR.MI', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('FTSEMIB.MI', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^IXBK', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^NBI', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^IXIC', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^IXK', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^IXFN', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^IXF', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^IXID', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^IXIS', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^NDX', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^IXUT', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^IXTR', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^OSEAX', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^IBEX', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('INDC.MC', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^OMX', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^OMXSPI', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^SSMI', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^MERV', 'False', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^MXX', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^STI', 'False', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^JKSE', 'False', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^KLSE', 'False', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^TWII', 'False', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^TA100', 'True', '');
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('INDB.MC', 'True', NULL);
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('IGBM.MA', 'True', NULL);
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('FPXAA.PR', 'False', NULL);
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('MICEXINDEXCF.ME', 'False', NULL);
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('GD.AT', 'False', NULL);
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^GSPC', 'False', NULL);
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^BATSK', 'False', NULL);
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^IPSA', 'False', NULL);
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^BSESN', 'False', NULL);
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^N225', 'False', NULL);
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('^KS11', 'False', NULL);
insert into cobo_mercados ("mercado", "habilitado", "descripcion") values ('PSEI.PS', 'False', NULL);
COMMIT;
;
BEGIN TRANSACTION;
insert into cobo_monedas ("codigo", "url_Inet", "descripcion", "valor", "fechaRegistro") values ('$', 'EURUSD=X', 'Dolar', '1.1196', '2015-03-01 18:22:17');
insert into cobo_monedas ("codigo", "url_Inet", "descripcion", "valor", "fechaRegistro") values ('ARS', 'EURARS=X', 'ARS', '9.763', '2015-03-01 18:22:19');
insert into cobo_monedas ("codigo", "url_Inet", "descripcion", "valor", "fechaRegistro") values ('AUS', 'EURAUD=X', 'Dolar Australiano', '1.4333', '2015-03-01 18:22:20');
insert into cobo_monedas ("codigo", "url_Inet", "descripcion", "valor", "fechaRegistro") values ('BRL', 'EURBRL=X', 'Brasileiro', '3.1837', '2015-03-01 18:22:21');
insert into cobo_monedas ("codigo", "url_Inet", "descripcion", "valor", "fechaRegistro") values ('CAD', 'EURCAD=X', 'Dolar Canada', '1.4003', '2015-03-01 18:22:22');
insert into cobo_monedas ("codigo", "url_Inet", "descripcion", "valor", "fechaRegistro") values ('CHF', 'EURCHF=X', 'Franco Suizo', '1.0677', '2015-03-01 18:22:23');
insert into cobo_monedas ("codigo", "url_Inet", "descripcion", "valor", "fechaRegistro") values ('CNY', 'EURCNY=X', 'Yuan Chino', '7.0148', '2015-03-01 18:22:25');
insert into cobo_monedas ("codigo", "url_Inet", "descripcion", "valor", "fechaRegistro") values ('DEN', 'EURDKK=X', 'Corona Danesa', '7.4615', '2015-03-01 18:22:27');
insert into cobo_monedas ("codigo", "url_Inet", "descripcion", "valor", "fechaRegistro") values ('E', 'EUREUR=X', 'Euro', '1', '2015-03-01 18:22:29');
insert into cobo_monedas ("codigo", "url_Inet", "descripcion", "valor", "fechaRegistro") values ('GBP', 'EURGBP=X', 'Libra Esterlina(Peniques)', '72.52', '2015-03-01 18:22:30');
insert into cobo_monedas ("codigo", "url_Inet", "descripcion", "valor", "fechaRegistro") values ('HKD', 'EURHKD=X', 'Dolar Hongkong', '8.6833', '2015-03-01 18:22:31');
insert into cobo_monedas ("codigo", "url_Inet", "descripcion", "valor", "fechaRegistro") values ('INR', 'EURINR=X', 'Rupia India', '69.0196', '2015-03-01 18:22:33');
insert into cobo_monedas ("codigo", "url_Inet", "descripcion", "valor", "fechaRegistro") values ('MXN', 'EURMXN=X', 'Peso Mexicano', '16.7334', '2015-03-01 18:22:35');
insert into cobo_monedas ("codigo", "url_Inet", "descripcion", "valor", "fechaRegistro") values ('MYR', 'EURMYR=X', 'Ringgit malayo', '4.0489', '2015-03-01 18:22:36');
insert into cobo_monedas ("codigo", "url_Inet", "descripcion", "valor", "fechaRegistro") values ('NOK', 'EURNOK=X', 'Corona noruega', '8.5878', '2015-03-01 18:22:38');
insert into cobo_monedas ("codigo", "url_Inet", "descripcion", "valor", "fechaRegistro") values ('SEK', 'EURSEK=X', 'Corona sueca', '9.3328', '2015-03-01 18:22:39');
insert into cobo_monedas ("codigo", "url_Inet", "descripcion", "valor", "fechaRegistro") values ('YEN', 'EURJPY=X', 'Yen Japones', '133.9437', '2015-03-01 18:22:40');
COMMIT;
;
BEGIN TRANSACTION;
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('1', 'NasdaqNM', '$', '2010-06-14 21:13:02');
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('2', 'NYSE', '$', '2010-06-14 21:13:08');
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('3', 'AMEX', '$', '2010-06-14 21:13:12');
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('4', 'NCM', '$', '2010-06-14 21:13:15');
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('5', 'Milan', 'E', '2010-06-08 23:16:34');
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('6', 'Brussels', 'E', '2010-06-08 23:16:40');
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('8', 'Paris', 'E', '2010-06-08 23:16:50');
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('9', 'MDD', 'E', '2010-06-08 23:16:55');
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('10', 'NGM', '$', '2010-06-14 21:13:24');
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('11', 'PCX', '$', '2010-06-14 21:13:31');
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('12', 'ENX', 'E', '2010-06-08 23:17:26');
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('13', 'Amsterdam', 'E', '2010-06-05 17:53:40');
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('14', 'XETRA', 'E', '2010-06-05 17:53:45');
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('15', 'Swiss', 'CHF', '2010-06-14 21:13:38');
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('16', 'MCE', 'E', '2010-06-05 17:53:58');
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('17', 'Irish', 'E', '2010-06-05 17:54:03');
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('18', 'London', 'GBP', '2010-06-14 21:13:45');
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('19', 'Oslo', 'NOK', '2010-06-14 21:13:53');
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('20', 'Stockholm', 'SEK', '2010-06-14 21:14:02');
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('21', 'Toronto', 'CAD', '2010-06-14 21:14:09');
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('22', 'VTX', 'CHF', '2010-06-14 21:14:26');
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('23', 'WCB', '$', '2010-08-14 12:54:39');
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('24', 'DJI', '$', '2010-08-14 12:55:00');
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('25', 'SNP', '$', '2010-08-14 12:55:06');
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('26', 'NasdaqSC', '$', '2010-08-14 12:55:16');
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('27', 'Lisbon', 'E', '2010-08-14 12:55:48');
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('28', 'FSI', 'GBP', '2010-08-14 12:56:32');
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('29', 'ASX', 'AUS', '2010-08-14 12:55:38');
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('30', 'NZSE', 'AUS', '2010-08-14 12:56:49');
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('31', 'CDNX', 'CAD', '2010-08-14 12:57:04');
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('32', 'HKSE', 'HKD', '2010-08-14 12:57:23');
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('33', 'Vienna', 'E', '2010-08-14 12:56:09');
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('34', 'Copenhagen', 'DEN', '2010-08-14 12:57:56');
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('35', 'PSX', 'E', NULL);
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('36', 'Other OTC', '$', NULL);
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('37', 'OTC BB', '$', NULL);
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('38', 'Shenzhen', 'CNY', NULL);
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('39', 'Shanghai', 'CNY', NULL);
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('40', 'Madrid', 'E', NULL);
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('41', 'Frankfurt', 'E', NULL);
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('42', 'Berlin', 'E', NULL);
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('43', 'Mexico', 'MXN', NULL);
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('44', 'Sao Paolo', 'BRL', NULL);
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('45', 'Buenos Aires', 'ARS', NULL);
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('46', 'Stuttgart', 'E', '2010-06-08 23:16:34');
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('47', 'Kuala Lumpur', 'MYR', '2010-06-08 23:16:34');
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('48', 'Munich', 'E', NULL);
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('49', 'Barcelona', 'E', NULL);
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('50', 'Valencia', 'E', NULL);
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('51', 'Bilbao', 'E', NULL);
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('52', 'Dusseldorf', 'E', NULL);
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('53', 'Hamburg', 'E', NULL);
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('54', 'Hanover', 'E', NULL);
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('55', 'EUX', 'GBP', NULL);
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('56', 'IOB', '$', NULL);
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('57', 'NIM', '$', '2013-04-18');
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('58', 'YHD', 'HKD', '2014-11-17');
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('66', 'LSE', 'GBP', NULL);
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('67', 'GER', 'E', NULL);
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('68', 'NYQ', '$', NULL);
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('69', 'BRU', 'E', NULL);
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('70', 'TOR', 'CAD', NULL);
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('71', 'MIL', 'E', NULL);
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('72', 'PAR', 'E', NULL);
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('73', 'NMS', '$', NULL);
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('74', 'STO', 'SEK', NULL);
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('75', 'CPH', 'DEN', NULL);
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('76', 'VIE', 'E', NULL);
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('77', 'OSL', 'NOK', NULL);
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('78', 'VAN', 'CAD', NULL);
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('79', 'ASE', '$', NULL);
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('80', 'LIS', 'E', NULL);
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('81', 'EBS', 'CHF', NULL);
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('82', 'PNK', '$', NULL);
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('83', 'HKG', 'HKD', NULL);
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('84', 'AMS', 'E', NULL);
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('85', 'ISE', 'E', NULL);
insert into cobo_mercado_moneda ("id", "nombreUrl", "abrevMoneda", "fechaRegistro") values ('86', 'OBB', '$', NULL);
COMMIT;
BEGIN TRANSACTION;
insert into cobo_configuracion ("codigo", "valor", "descripcion") values ('difdiasactualizacion', '10', 'Numero de dias que tienen que pasar para que se considere un historico pendiente de actualizacion');
COMMIT;